version: '3.9'
services:
  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=programminghero
      - POSTGRES_PASSWORD=programminghero123
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    restart: always
    depends_on:
      - postgres
    ports:
      - 4000:8080

volumes:
  db:
    driver: local
