version: '3.8'
services:
  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: auuntoo@auuntoo.com
      PGADMIN_DEFAULT_PASSWORD: auuntoo
    ports:
      - '4001:80'
