version: '3.8'

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: auuntoo
      MYSQL_DATABASE: otel_db
      MYSQL_USER: auuntoo
      MYSQL_PASSWORD: auuntoo
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - 4001:80
    depends_on:
      - mysql

volumes:
  mysql_data:
