version: "3"
services:

  db:
    image: mysql:latest
    container_name: mysql
    volumes: 
      - ./db_data:/var/lib/mysql
    ports:
      - 3306:3306
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: auuntoo
      # MYSQL_DATABASE: cromwell
      MYSQL_USER: auuntoo
      MYSQL_PASSWORD: auuntoo

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpadmin
    environment:
      PMA_HOST: db
    links:
      - db:db
    ports:
      - 4001:80
    restart: unless-stopped