version: '3.7'

services:
  mongo:
    image: mongo
    restart: always
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: auuntoo
      MONGO_INITDB_ROOT_PASSWORD: auuntoo
      #MONGODB_AUTH_DATABASE: admin
    ports:
      - '27017:27017'
    volumes:
      - ./workspace:/workspace
      - type: volume
        source: mongodb_data_volume
        target: /data/db

  # mongo-express:
  #   image: mongo-express
  #   container_name: mongo-express
  #   restart: always
  #   ports:
  #     - '28081:8081'
  #   environment:
  #     ME_CONFIG_MONGODB_SERVER: mongo
  #     ME_CONFIG_BASICAUTH_USERNAME: admin
  #     ME_CONFIG_BASICAUTH_PASSWORD: 123456
  #     #ME_CONFIG_MONGODB_AUTH_DATABASE: admin
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: mongoadmin
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: mongoadmin
  #     ME_CONFIG_MONGODB_URL: mongo://mongoadmin:mongoadmin@mongo:27017/
  #   depends_on:
  #     - mongo

volumes:
  mongodb_data_volume:
    driver: local
